



# HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
# Secret ?? ?? ???? Base64 ? ???? ? ?? (?? ???? ???? ??? ??? ??)
# $ echo 'spring-boot-security-jwt-tutorial-jiwoon-spring-boot-security-jwt-tutorial' | base64
